### ISSUE TITLE
Unable to install on Debian buster

### ISSUE THREAD

**Issue by jsbien** [jbaiter/hocrviewer-mirador#5]
The fatal error is:
` python3 hocrviewer.py serve hocr`
`Traceback (most recent call last):`
`  File "hocrviewer.py", line 11, in <module>`
`    import click_log`
I've got also the following messages:
`iiif-prezi 0.2.9 has requirement Pillow<4.0.0,>=3.2.0, but you'll have pillow 5.4.1 which is incompatible.`
`The script flask is installed in '/home/jsbien/.local/bin' which is not on PATH.`

How to solve or circumvent the problem?

Best regards

Janusz

**Comment by jsbien** [comment]
The click_log problem was solved by installing python3-click-log. Now I'm confused by the following problem:
`printenv PATH`
`/home/jsbien/.local/bin:/home/jsbien/.nvm/versions/node/v8.1.4/bin:/home/jsbien/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
`python3 hocrviewer.py serve hocr`
`Traceback (most recent call last):`
`  File "hocrviewer.py", line 12, in <module>`
`    import flask`
`ModuleNotFoundError: No module named 'flask`
The flask is now in the path, why it is not found? Any relation to the pillow incompatibility message?

**Comment by jsbien** [comment]
It was python version confusion. This
`pip3 install -r requirements.txt`
works.
